In [2]:
import numpy as np
import pandas as pd
import importlib
import sys
import os

# our custom utilities
analysis_base_dir = '/Users/davidhalpern/Documents/GitHub/identifying_causal_subsequent_memory_effects/'
analysis_dir = analysis_base_dir + 'preproc/'
mri_preproc_dir = analysis_base_dir + 'preproc/'
data_base_dir = '/Volumes/Seagate/glm_csvs/'
data_dir = analysis_base_dir + 'data/'

sys.path.append(analysis_base_dir + 'modules/')
import analysis_utils as au
importlib.reload(au)

# Schaefer

In [270]:
schaefer_rois = range(1, 101)
var_group = 'schaefer'
roi_col = 'roi_num_schaeffer'

## Univariate Activity

In [272]:
schaefer_activity_df_long = au.create_long_activity_df(schaefer_rois, base_dir=data_base_dir, 
                                           var_group=var_group, roi_col=roi_col)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100

In [273]:
schaefer_activity_df_long.to_csv((data_base_dir + 'schaefer_activity_long_df.csv'), index=False)

In [116]:
schaefer_activity_df_long = pd.read_csv(data_base_dir + 'schaefer_activity_long_df.csv')

## Pattern Similarity

In [275]:
schaefer_pattern_corr_df_long_lt = au.create_lt_pattern_sim_df(schaefer_rois, 
                                                      base_dir=data_base_dir, 
                                                   var_group=var_group, 
                                                   roi_col=roi_col)
schaefer_pattern_corr_df_long_lt.to_csv(data_base_dir + var_group + '_pattern_corr_df_long_lt.csv', index=False)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100

In [86]:
schaefer_pattern_corr_df_long_lt = pd.read_csv(data_base_dir + 'schaefer_pattern_corr_df_long_lt.csv')

In [276]:
schaefer_pattern_corr_df_long_lt.head()

,sub_id,roi,corr,lith_word_1,study_block_1,lith_word_2,study_block_2,within_cross,fisher_z
1,sub-11,1,0.127849,akis,2,akis,1,Within,0.128553
2,sub-11,1,0.309759,akis,3,akis,1,Within,0.320279
3,sub-11,1,-0.031933,akis,4,akis,1,Within,-0.031944
4,sub-11,1,0.071297,akis,5,akis,1,Within,0.071419
6,sub-11,1,0.049322,arbata,2,akis,1,Cross,0.049362

In [277]:
schaefer_pattern_corr_df_long = au.create_long_pattern_sim_df(
    schaefer_pattern_corr_df_long_lt, var_group=var_group, use_chunks=True)

start
use_chunks
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100

In [278]:
schaefer_pattern_corr_df_long#.drop(columns=['within_cross'], inplace=True)

,sub_id,roi,lith_word,study_block,value,var,var_group
0,sub-11,1,akis,1_2,0.060886,pattern_sim_z_Cross,schaefer
1,sub-11,1,akis,1_3,-0.004447,pattern_sim_z_Cross,schaefer
2,sub-11,1,akis,1_4,-0.030133,pattern_sim_z_Cross,schaefer
3,sub-11,1,akis,1_5,0.001047,pattern_sim_z_Cross,schaefer
4,sub-11,1,akis,2_1,0.093528,pattern_sim_z_Cross,schaefer
...,...,...,...,...,...,...,...
76945,sub-79,100,zele,2_4,0.642030,pattern_sim_z_Within,schaefer
76946,sub-79,100,zele,2_5,-0.341018,pattern_sim_z_Within,schaefer
76947,sub-79,100,zele,3_4,0.349258,pattern_sim_z_Within,schaefer
76948,sub-79,100,zele,3_5,-0.004170,pattern_sim_z_Within,schaefer
76949,sub-79,100,zele,4_5,-0.457005,pattern_sim_z_Within,schaefer

In [279]:
schaefer_pattern_corr_df_long.to_csv(data_base_dir + 'schaefer_pattern_corr_df_long.csv')

In [117]:
schaefer_pattern_corr_df_long = pd.read_csv(data_base_dir + 'schaefer_pattern_corr_df_long.csv')

## Inter-subject Correlation

In [281]:
schaefer_ISC_df_long = au.create_long_ISC_df(schaefer_rois, base_dir=data_base_dir, 
                                           var_group=var_group, roi_col=roi_col)
schaefer_ISC_df_long.to_csv(data_base_dir + var_group + '_ISC_df_long.csv', index=False)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100

In [118]:
schaefer_ISC_df_long = pd.read_csv(data_base_dir + 'schaefer_ISC_df_long.csv')

# Whole Brain

In [282]:
activity_df_long = pd.read_csv(data_base_dir + 'schaefer_activity_long_df.csv')

### Activity

In [283]:
wb_activity_df_long = activity_df_long.groupby(['sub_id', 'lith_word', 'var', 'study_block']).agg({'value': 'mean'}).reset_index()
wb_activity_df_long['roi'] = 'whole_brain'
wb_activity_df_long['var_group'] = 'whole_brain_schaefer'

### Pattern Similarity

In [284]:
wb_pattern_corr_df = au.get_pattern_corr_df(activity_df_long, 
                    values='value', 
                    columns=['lith_word', 'study_block'],
                    group_index=['sub_id'], 
                    corr_index=['roi'],
                   lower_triangular=False)
wb_pattern_corr_df = wb_pattern_corr_df[wb_pattern_corr_df['study_block_1'] != wb_pattern_corr_df['study_block_2']]
wb_pattern_corr_df = wb_pattern_corr_df.drop(columns=['lith_word_study_block_1', 'lith_word_study_block_2'])

In [285]:
wb_pattern_corr_df['within_cross'] = 'Cross'
wb_pattern_corr_df.loc[wb_pattern_corr_df['lith_word_1'] == wb_pattern_corr_df['lith_word_2'], 'within_cross'] = 'Within'
wb_pattern_corr_df['fisher_z'] = np.arctanh(wb_pattern_corr_df['corr'])

In [286]:
wb_pattern_corr_df

,sub_id,corr,lith_word_1,study_block_1,lith_word_2,study_block_2,within_cross,fisher_z
1,sub-11,-0.335775,akis,2,akis,1,Within,-0.349323
2,sub-11,0.634164,akis,3,akis,1,Within,0.748351
3,sub-11,-0.071043,akis,4,akis,1,Within,-0.071163
4,sub-11,-0.317569,akis,5,akis,1,Within,-0.328941
6,sub-11,0.375141,arbata,2,akis,1,Cross,0.394393
...,...,...,...,...,...,...,...,...
2885618,sub-79,-0.076245,varpas,4,zele,5,Cross,-0.076393
2885620,sub-79,0.045122,zele,1,zele,5,Within,0.045153
2885621,sub-79,-0.156598,zele,2,zele,5,Within,-0.157897
2885622,sub-79,-0.042763,zele,3,zele,5,Within,-0.042789
2885623,sub-79,0.186986,zele,4,zele,5,Within,0.189212

In [287]:
wb_pattern_corr_df['min_study_block'] = wb_pattern_corr_df[['study_block_1', 'study_block_2']].min(axis=1)
wb_pattern_corr_df['max_study_block'] = wb_pattern_corr_df[['study_block_1', 'study_block_2']].max(axis=1)
wb_pattern_corr_df['study_block'] = wb_pattern_corr_df['study_block_1'].astype(str) + '_' + wb_pattern_corr_df['study_block_2'].astype(str)
wb_pattern_corr_df.loc[(wb_pattern_corr_df['within_cross'] == 'Within'), 'study_block'] = wb_pattern_corr_df['min_study_block'].astype(str) + '_' + wb_pattern_corr_df['max_study_block'].astype(str)

In [288]:
wb_pattern_corr_df = wb_pattern_corr_df.groupby(['sub_id', 'lith_word_1', 'within_cross', 'study_block']).agg({'fisher_z': 'mean'}).reset_index()

In [289]:
wb_pattern_corr_df = wb_pattern_corr_df.rename(columns={'lith_word_1': 'lith_word', 'fisher_z': 'value'})
wb_pattern_corr_df['var'] = 'pattern_sim_z_' + wb_pattern_corr_df['within_cross'].astype(str)
wb_pattern_corr_df = wb_pattern_corr_df.drop(columns=['within_cross'])
wb_pattern_corr_df['roi'] = 'whole_brain'
wb_pattern_corr_df['var_group'] = 'whole_brain_schaefer'

In [290]:
wb_pattern_corr_df_long = wb_pattern_corr_df

### ISC

In [291]:
pattern_df_pivot = pd.pivot_table(activity_df_long, 
                                      values='value', 
                                      index=['lith_word', 'study_block', 'roi'],
                                      columns=['sub_id']).reset_index()
wb_ISC_df_long = pattern_df_pivot.drop(columns=['roi']).groupby(
        ['lith_word', 'study_block']).corr().reset_index()
wb_ISC_melt = wb_ISC_df_long.melt(
        id_vars=['lith_word', 'study_block', 'sub_id'],
        value_vars=pattern_df_pivot.columns[3:], #subject cols
        var_name='sub_id_2',
        value_name='corr').dropna()

In [292]:
wb_ISC_melt['fisher_z'] = np.arctanh(wb_ISC_melt['corr'])
wb_ISC_melt = wb_ISC_melt.query('sub_id != sub_id_2')
wb_ISC_df = wb_ISC_melt.groupby(['lith_word', 'sub_id', 'study_block']).agg({'fisher_z': 'mean'}).reset_index()

In [293]:
wb_ISC_df = wb_ISC_df.rename(columns={'fisher_z': 'value'})
wb_ISC_df['var'] = 'ISC_z'
wb_ISC_df['roi'] = 'whole_brain'
wb_ISC_df['var_group'] = 'whole_brain_schaefer'

In [294]:
wb_ISC_df_long = wb_ISC_df

# Targeted ROIs

In [295]:
vox_coord_df = pd.read_csv(os.path.join(analysis_base_dir, 'mri_code', 'roi_info', 'vox_coord_mapper.csv'))

/Users/davidhalpern/opt/anaconda3/envs/py37/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3072: DtypeWarning: Columns (8) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [296]:
bad_rois = ["left_PRC", "right_PRC"]
targeted_rois = vox_coord_df.query('roi_name == roi_name and roi_name != @bad_rois').roi_name.unique()
targeted_rois

array(['left_insula2', 'left_ATL', 'left_RSC', 'right_Precuneus',
       'right_RSC', 'right_ParietalDorsal', 'right_ParietalMid',
       'right_LO', 'left_LO', 'left_Precuneus', 'left_insula1',
       'left_VWFA', 'left_ParietalDorsal', 'left_VLPFCUpper',
       'left_ParietalMid', 'left_VLPFCLower', 'right_ATL'], dtype=object)

In [297]:
var_group = 'tr'
roi_col = 'roi_name'

## Activity

In [299]:
tr_activity_df_long = au.create_long_activity_df(targeted_rois, base_dir=data_base_dir, 
                                           var_group=var_group, roi_col=roi_col)

left_insula2
left_ATL
left_RSC
right_Precuneus
right_RSC
right_ParietalDorsal
right_ParietalMid
right_LO
left_LO
left_Precuneus
left_insula1
left_VWFA
left_ParietalDorsal
left_VLPFCUpper
left_ParietalMid
left_VLPFCLower
right_ATL

In [300]:
tr_activity_df_long.to_csv(data_base_dir + var_group + '_activity_long_df.csv', index=False)

In [132]:
tr_activity_df_long = pd.read_csv(data_base_dir + 'tr_activity_long_df.csv')

## Pattern similarity

In [302]:
importlib.reload(au)
tr_pattern_corr_df_long_lt = au.create_lt_pattern_sim_df(targeted_rois, 
                                                      base_dir=data_base_dir, 
                                                   var_group=var_group, 
                                                   roi_col=roi_col)
tr_pattern_corr_df_long_lt.to_csv(data_base_dir + var_group + '_pattern_corr_df_long_lt.csv', index=False)

left_insula2
left_ATL
left_RSC
right_Precuneus
right_RSC
right_ParietalDorsal
right_ParietalMid
right_LO
left_LO
left_Precuneus
left_insula1
left_VWFA
left_ParietalDorsal
left_VLPFCUpper
left_ParietalMid
left_VLPFCLower
right_ATL

In [117]:
tr_pattern_corr_df_long_lt = pd.read_csv(data_base_dir + 'tr_pattern_corr_df_long_lt.csv')

In [303]:
tr_pattern_corr_df_long = au.create_long_pattern_sim_df(tr_pattern_corr_df_long_lt, var_group=var_group)

start

In [304]:
tr_pattern_corr_df_long.to_csv(data_base_dir + var_group + '_pattern_sim_long_df.csv', index=False)

In [133]:
tr_pattern_corr_df_long = pd.read_csv(data_base_dir + 'tr_pattern_sim_long_df.csv')

## ISC

In [305]:
tr_ISC_df_long = au.create_long_ISC_df(targeted_rois, base_dir=data_base_dir, var_group=var_group, 
                                 roi_col=roi_col)
tr_ISC_df_long.to_csv(data_base_dir + var_group + '_ISC_df_long.csv', index=False)

left_insula2
left_ATL
left_RSC
right_Precuneus
right_RSC
right_ParietalDorsal
right_ParietalMid
right_LO
left_LO
left_Precuneus
left_insula1
left_VWFA
left_ParietalDorsal
left_VLPFCUpper
left_ParietalMid
left_VLPFCLower
right_ATL

In [134]:
tr_ISC_df_long = pd.read_csv(data_base_dir + 'tr_ISC_df_long.csv')

# Hippocampus

In [227]:
all_hipp_word_df = pd.read_csv(data_base_dir + '/all_hipp_df.csv')

In [228]:
all_hipp_word_df.study_block = all_hipp_word_df.study_block.astype(int)

In [229]:
all_hipp_word_df.groupby(['xyz']).size().max()

12825

In [230]:
all_hipp_size_df = all_hipp_word_df.groupby(['xyz', 'sub_id', 'lith_word']).size().rename('size').reset_index()

In [231]:
all_hipp_size_df.query('size == 6')

Empty DataFrame
Columns: [xyz, sub_id, lith_word, size]
Index: []

## Voxel activity

In [251]:
hipp_vox_activity_df = all_hipp_word_df.query('n_sub_runs == 285')[['xyz', 'value', 'roi_name', 'study_block', 'sub_id', 'lith_word']]

In [252]:
hipp_vox_activity_df

,xyz,value,roi_name,study_block,sub_id,lith_word
4,27_47_22,-0.574696,Hipp_L_ant_reslicedBin,1,sub-11,pastatas
5,27_47_23,-1.055099,Hipp_L_ant_reslicedBin,1,sub-11,pastatas
6,27_47_24,-0.683541,Hipp_L_ant_reslicedBin,1,sub-11,pastatas
8,27_48_22,0.255924,Hipp_L_ant_reslicedBin,1,sub-11,pastatas
9,27_48_23,-0.612949,Hipp_L_ant_reslicedBin,1,sub-11,pastatas
...,...,...,...,...,...,...
3725403,49_40_28,-1.275691,Hipp_R_post_reslicedBin,5,sub-75,vaistas
3725435,49_40_28,0.262981,Hipp_R_post_reslicedBin,5,sub-76,vaistas
3725468,49_40_28,-1.930969,Hipp_R_post_reslicedBin,5,sub-77,vaistas
3725501,49_40_28,-1.661833,Hipp_R_post_reslicedBin,5,sub-78,vaistas
3725534,49_40_28,0.757168,Hipp_R_post_reslicedBin,5,sub-79,vaistas

In [240]:
# count_df = hipp_vox_activity_df.groupby(['xyz', 'study_block']).count().reset_index()
# bad_voxs = count_df.query('value != 2565')['xyz']
# hipp_vox_activity_df.query('xyz not in @bad_voxs', inplace=True)

In [253]:
hipp_vox_activity_df['roi'] = 'hipp_' + hipp_vox_activity_df['xyz'].astype(str)
hipp_vox_activity_df = hipp_vox_activity_df.drop(columns=['xyz', 'roi_name'])
hipp_vox_activity_df['var'] = 'activity'
hipp_vox_activity_df['var_group'] = 'hipp_vox'

## Sub/Whole activity

In [254]:
hipp_sub_activity_df = all_hipp_word_df.groupby(
            ['sub_id', 'lith_word', 'roi_name', 'study_block']
            ).agg({'value': 'mean'}).reset_index()
hipp_sub_activity_df['var'] = 'activity'
hipp_sub_activity_df.rename(columns={'roi_name': 'roi'}, inplace=True)
hipp_sub_activity_df['var_group'] = 'hipp_sub'
hipp_sub_activity_df

,sub_id,lith_word,roi,study_block,value,var,var_group
0,sub-11,akis,Hipp_L_ant_reslicedBin,1,0.355314,activity,hipp_sub
1,sub-11,akis,Hipp_L_ant_reslicedBin,2,0.230793,activity,hipp_sub
2,sub-11,akis,Hipp_L_ant_reslicedBin,3,0.611829,activity,hipp_sub
3,sub-11,akis,Hipp_L_ant_reslicedBin,4,0.442371,activity,hipp_sub
4,sub-11,akis,Hipp_L_ant_reslicedBin,5,-0.617240,activity,hipp_sub
...,...,...,...,...,...,...,...
76945,sub-79,zele,Hipp_R_post_reslicedBin,1,-0.211325,activity,hipp_sub
76946,sub-79,zele,Hipp_R_post_reslicedBin,2,0.185626,activity,hipp_sub
76947,sub-79,zele,Hipp_R_post_reslicedBin,3,-0.491216,activity,hipp_sub
76948,sub-79,zele,Hipp_R_post_reslicedBin,4,0.022155,activity,hipp_sub
76949,sub-79,zele,Hipp_R_post_reslicedBin,5,0.221748,activity,hipp_sub

In [255]:
hipp_whole_activity_df = all_hipp_word_df.groupby(
            ['sub_id', 'lith_word', 'study_block']
            ).agg({'value': 'mean'}).reset_index()
hipp_whole_activity_df['var'] = 'activity'
hipp_whole_activity_df['roi'] = 'whole_hipp'
hipp_whole_activity_df['var_group'] = 'whole_hipp'

## Sub/Whole Pattern Similarity

In [257]:
hipp_whole_pattern_corr_df_lt = au.get_pattern_corr_df(
    all_hipp_word_df, 
                    values='value', 
                    columns=['lith_word', 'study_block'],
                    group_index=['sub_id'], 
                    corr_index=['xyz'])

In [258]:
hipp_whole_pattern_corr_df_lt = hipp_whole_pattern_corr_df_lt[hipp_whole_pattern_corr_df_lt['study_block_1'] != hipp_whole_pattern_corr_df_lt['study_block_2']]
hipp_whole_pattern_corr_df_lt = hipp_whole_pattern_corr_df_lt.drop(columns=['lith_word_study_block_1', 'lith_word_study_block_2']) 
hipp_whole_pattern_corr_df_lt['within_cross'] = 'Cross'
hipp_whole_pattern_corr_df_lt.loc[hipp_whole_pattern_corr_df_lt['lith_word_1'] == hipp_whole_pattern_corr_df_lt['lith_word_2'], 'within_cross'] = 'Within'
hipp_whole_pattern_corr_df_lt['fisher_z'] = np.arctanh(hipp_whole_pattern_corr_df_lt['corr'])

In [259]:
hipp_whole_pattern_corr_df = au.create_long_pattern_sim_df(hipp_whole_pattern_corr_df_lt, 'hipp_whole', sub_col='sub_id', 
    item_col='lith_word', use_roi_col=False, use_chunks=False)

start

In [260]:
hipp_whole_pattern_corr_df['roi'] = 'whole_hipp'

In [261]:
hipp_whole_pattern_corr_df_long = hipp_whole_pattern_corr_df

In [262]:
hipp_sub_pattern_corr_df_lt = au.get_pattern_corr_df(all_hipp_word_df, 
                                                       values='value',
                                         corr_index=['xyz'],
                                         columns=['lith_word', 'study_block'],
                                         group_index=['sub_id', 'roi_name'])

In [263]:
hipp_sub_pattern_corr_df_lt = hipp_sub_pattern_corr_df_lt[hipp_sub_pattern_corr_df_lt['study_block_1'] != hipp_sub_pattern_corr_df_lt['study_block_2']]
hipp_sub_pattern_corr_df_lt = hipp_sub_pattern_corr_df_lt.drop(columns=['lith_word_study_block_1', 'lith_word_study_block_2']) 
hipp_sub_pattern_corr_df_lt['within_cross'] = 'Cross'
hipp_sub_pattern_corr_df_lt.loc[hipp_sub_pattern_corr_df_lt['lith_word_1'] == hipp_sub_pattern_corr_df_lt['lith_word_2'], 'within_cross'] = 'Within'
hipp_sub_pattern_corr_df_lt['fisher_z'] = np.arctanh(hipp_sub_pattern_corr_df_lt['corr'])
hipp_sub_pattern_corr_df_lt.rename(columns={'roi_name': 'roi'}, inplace=True)

In [264]:
hipp_sub_pattern_corr_df = au.create_long_pattern_sim_df(hipp_sub_pattern_corr_df_lt, 
                                                         'hipp_sub', sub_col='sub_id', 
                                                         item_col='lith_word',
                                                         use_chunks=False)

start

In [265]:
hipp_sub_pattern_corr_df_long = hipp_sub_pattern_corr_df

## ISC

In [266]:
hipp_whole_pattern_df_pivot = pd.pivot_table(hipp_vox_activity_df, 
                                      values='value', 
                                      index=['lith_word', 'study_block', 'roi'],
                                      columns=['sub_id']).reset_index()
hipp_whole_ISC_df_long = hipp_whole_pattern_df_pivot.drop(columns=['roi']).groupby(
        ['lith_word', 'study_block']).corr().reset_index()
hipp_whole_ISC_melt = hipp_whole_ISC_df_long.melt(
        id_vars=['lith_word', 'study_block', 'sub_id'],
        value_vars=hipp_whole_pattern_df_pivot.columns[3:], 
        var_name='sub_id_2',
        value_name='corr').dropna()

In [267]:
hipp_whole_ISC_melt['fisher_z'] = np.arctanh(hipp_whole_ISC_melt['corr'])
hipp_whole_ISC_melt = hipp_whole_ISC_melt.query('sub_id != sub_id_2')
hipp_whole_ISC_df = hipp_whole_ISC_melt.groupby(['lith_word', 'sub_id', 'study_block']).agg({'fisher_z': 'mean'}).reset_index()

In [268]:
hipp_whole_ISC_df = hipp_whole_ISC_df.rename(columns={'fisher_z': 'value'})
hipp_whole_ISC_df['var'] = 'ISC_z'
hipp_whole_ISC_df['roi'] = 'whole_hipp'
hipp_whole_ISC_df['var_group'] = 'hipp_whole'

In [269]:
hipp_whole_ISC_df

      lith_word  sub_id  study_block     value    var         roi   var_group
0          akis  sub-11            1  0.012755  ISC_z  whole_hipp  hipp_whole
1          akis  sub-11            2  0.000662  ISC_z  whole_hipp  hipp_whole
2          akis  sub-11            3  0.076620  ISC_z  whole_hipp  hipp_whole
3          akis  sub-11            4  0.022687  ISC_z  whole_hipp  hipp_whole
4          akis  sub-11            5 -0.053637  ISC_z  whole_hipp  hipp_whole
...         ...     ...          ...       ...    ...         ...         ...
12820      zele  sub-79            1 -0.049896  ISC_z  whole_hipp  hipp_whole
12821      zele  sub-79            2  0.014786  ISC_z  whole_hipp  hipp_whole
12822      zele  sub-79            3  0.055854  ISC_z  whole_hipp  hipp_whole
12823      zele  sub-79            4  0.058597  ISC_z  whole_hipp  hipp_whole
12824      zele  sub-79            5  0.004528  ISC_z  whole_hipp  hipp_whole

[12825 rows x 7 columns]

# Classifier DataFrame

In [306]:
dfs = [schaefer_activity_df_long, schaefer_pattern_corr_df_long, schaefer_ISC_df_long, 
       wb_activity_df_long, wb_pattern_corr_df_long, wb_ISC_df_long,
#         xue_activity_df_long, xue_pattern_corr_df_long, xue_ISC_df_long,
       tr_activity_df_long, tr_pattern_corr_df_long, tr_ISC_df_long,
       hipp_vox_activity_df, hipp_sub_activity_df, hipp_whole_activity_df,
       hipp_sub_pattern_corr_df, 
       hipp_whole_pattern_corr_df, hipp_whole_ISC_df
      ]
classifier_df = pd.concat(dfs)

In [307]:
classifier_df.head()

   sub_id study_block roi lith_word     value       var var_group
0  sub-11           1   1      akis -0.204746  activity  schaefer
1  sub-11           1   1    arbata  0.123581  activity  schaefer
2  sub-11           1   1     batas -0.264001  activity  schaefer
3  sub-11           1   1    bugnas  0.255153  activity  schaefer
4  sub-11           1   1     burna  1.353574  activity  schaefer

In [209]:
# classifier_df.drop(columns=['Unnamed: 0'], inplace=True)

In [308]:
classifier_df['roi'] = classifier_df['roi'].astype(str)
classifier_df['study_block'] = classifier_df['study_block'].astype(str)

In [309]:
with pd.option_context("display.max_rows", 1000, "display.max_columns", 5):
    display(classifier_df.groupby(['var', 'var_group', 'roi']).size())

var                   var_group             roi
ISC_z                 hipp_whole            whole_hipp                 12825
                      schaefer              1                          12825
                                            10                         12825
                                            100                        12825
                                            11                         12825
                                            12                         12825
                                            13                         12825
                                            14                         12825
                                            15                         12825
                                            16                         12825
                                            17                         12825
                                            18                         12825
                                            19                         12825
                                            2                          12825
                                            20                         12825
                                            21                         12825
                                            22                         12825
                                            23                         12825
                                            24                         12825
                                            25                         12825
                                            26                         12825
                                            27                         12825
                                            28                         12825
                                            29                         12825
                                            3                          12825
                                            30                         12825
                                            31                         12825
                                            32                         12825
                                            33                         12825
                                            34                         12825
                                            35                         12825
                                            36                         12825
                                            37                         12825
                                            38                         12825
                                            39                         12825
                                            4                          12825
                                            40                         12825
                                            41                         12825
                                            42                         12825
                                            43                         12825
                                            44                         12825
                                            45                         12825
                                            46                         12825
                                            47                         12825
                                            48                         12825
                                            49                         12825
                                            5                          12825
                                            50                         12825
                                            51                         12825
                                            52                         12825
                                            53                         12825
                                            54                         12825
                                            55                         12825
                                            56                         12825
                                            57                         12825
                                            58                         12825
                                            59                         12825
                                            6                          12825
                                            60                         12825
                                            61                         12825
                                            62                         12825
                                            63                         12825
                                            64                         12825
                                            65                         12825
                                            66                         12825
                                            67                         12825
                                            68                         12825
                                            69                         12825
                                            7                          12825
                                            70                         12825
                                            71                         12825
                                            72                         12825
                                            73                         12825
                                            74                         12825
                                            75                         12825
                                            76                         12825
                                            77                         12825
                                            78                         12825
                                            79                         12825
                                            8                          12825
                                            80                         12825
                                            81                         12825
                                            82                         12825
                                            83                         12825
                                            84                         12825
                                            85                         12825
                                            86                         12825
                                            87                         12825
                                            88                         12825
                                            89                         12825
                                            9                          12825
                                            90                         12825
                                            91                         12825
                                            92                         12825
                                            93                         12825
                                            94                         12825
                                            95                         12825
                                            96                         12825
                                            97                         12825
                                            98                         12825
                                            99                         12825
                      tr                    left_ATL                   12825
                                            left_LO                    12825
                                            left_ParietalDorsal        12825
                                            left_ParietalMid           12825
                                            left_Precuneus             12825
                                            left_RSC                   12825
                                            left_VLPFCLower            12825
                                            left_VLPFCUpper            12825
                                            left_VWFA                  12825
                                            left_insula1               12825
                                            left_insula2               12825
                                            right_ATL                  12825
                                            right_LO                   12825
                                            right_ParietalDorsal       12825
                                            right_ParietalMid          12825
                                            right_Precuneus            12825
                                            right_RSC                  12825
                      whole_brain_schaefer  whole_brain                12825
activity              hipp_sub              Hipp_L_ant_reslicedBin     12825
                                            Hipp_L_mid_reslicedBin     12825
                                            Hipp_L_post_reslicedBin    12825
                                            Hipp_R_ant_reslicedBin     12825
                                            Hipp_R_mid_reslicedBin     12825
                                            Hipp_R_post_reslicedBin    12825
                      hipp_vox              hipp_26_43_25              12825
                                            hipp_26_44_25              12825
                                            hipp_27_42_26              12825
                                            hipp_27_43_25              12825
                                            hipp_27_43_26              12825
                                            hipp_27_44_24              12825
                                            hipp_27_44_25              12825
                                            hipp_27_44_26              12825
                                            hipp_27_47_22              12825
                                            hipp_27_47_23              12825
                                            hipp_27_47_24              12825
                                            hipp_27_48_22              12825
                                            hipp_27_48_23              12825
                                            hipp_28_39_28              12825
                                            hipp_28_42_26              12825
                                            hipp_28_43_25              12825
                                            hipp_28_44_24              12825
                                            hipp_28_44_25              12825
                                            hipp_28_47_22              12825
                                            hipp_28_47_23              12825
                                            hipp_28_47_24              12825
                                            hipp_28_48_22              12825
                                            hipp_28_48_23              12825
                                            hipp_28_49_22              12825
                                            hipp_29_47_22              12825
                                            hipp_29_47_23              12825
                                            hipp_29_47_24              12825
                                            hipp_29_48_22              12825
                                            hipp_29_48_23              12825
                                            hipp_29_49_22              12825
                                            hipp_30_47_22              12825
                                            hipp_30_47_23              12825
                                            hipp_30_47_24              12825
                                            hipp_30_48_22              12825
                                            hipp_30_48_23              12825
                                            hipp_30_49_22              12825
                                            hipp_30_49_23              12825
                                            hipp_31_48_22              12825
                                            hipp_31_48_23              12825
                                            hipp_45_49_23              12825
                                            hipp_46_48_23              12825
                                            hipp_46_49_22              12825
                                            hipp_46_49_23              12825
                                            hipp_46_50_22              12825
                                            hipp_47_48_22              12825
                                            hipp_47_48_23              12825
                                            hipp_47_49_22              12825
                                            hipp_48_44_25              12825
                                            hipp_48_45_24              12825
                                            hipp_48_45_25              12825
                                            hipp_48_48_22              12825
                                            hipp_48_48_23              12825
                                            hipp_48_49_22              12825
                                            hipp_49_40_28              12825
                                            hipp_49_43_26              12825
                                            hipp_49_44_25              12825
                                            hipp_49_44_26              12825
                                            hipp_49_45_24              12825
                                            hipp_49_45_25              12825
                                            hipp_49_48_22              12825
                                            hipp_49_48_23              12825
                                            hipp_49_49_21              12825
                                            hipp_49_49_22              12825
                                            hipp_50_42_26              12825
                                            hipp_50_42_27              12825
                                            hipp_50_43_25              12825
                                            hipp_50_43_26              12825
                                            hipp_50_44_24              12825
                                            hipp_50_44_25              12825
                                            hipp_50_44_26              12825
                                            hipp_50_45_24              12825
                                            hipp_50_45_25              12825
                                            hipp_50_48_22              12825
                                            hipp_50_48_23              12825
                      schaefer              1                          12825
                                            10                         12825
                                            100                        12825
                                            11                         12825
                                            12                         12825
                                            13                         12825
                                            14                         12825
                                            15                         12825
                                            16                         12825
                                            17                         12825
                                            18                         12825
                                            19                         12825
                                            2                          12825
                                            20                         12825
                                            21                         12825
                                            22                         12825
                                            23                         12825
                                            24                         12825
                                            25                         12825
                                            26                         12825
                                            27                         12825
                                            28                         12825
                                            29                         12825
                                            3                          12825
                                            30                         12825
                                            31                         12825
                                            32                         12825
                                            33                         12825
                                            34                         12825
                                            35                         12825
                                            36                         12825
                                            37                         12825
                                            38                         12825
                                            39                         12825
                                            4                          12825
                                            40                         12825
                                            41                         12825
                                            42                         12825
                                            43                         12825
                                            44                         12825
                                            45                         12825
                                            46                         12825
                                            47                         12825
                                            48                         12825
                                            49                         12825
                                            5                          12825
                                            50                         12825
                                            51                         12825
                                            52                         12825
                                            53                         12825
                                            54                         12825
                                            55                         12825
                                            56                         12825
                                            57                         12825
                                            58                         12825
                                            59                         12825
                                            6                          12825
                                            60                         12825
                                            61                         12825
                                            62                         12825

In [310]:
classifier_df.groupby(['var', 'var_group']).head()

    sub_id study_block         roi lith_word     value       var   var_group
0   sub-11           1           1      akis -0.204746  activity    schaefer
1   sub-11           1           1    arbata  0.123581  activity    schaefer
2   sub-11           1           1     batas -0.264001  activity    schaefer
3   sub-11           1           1    bugnas  0.255153  activity    schaefer
4   sub-11           1           1     burna  1.353574  activity    schaefer
..     ...         ...         ...       ...       ...       ...         ...
0   sub-11           1  whole_hipp      akis  0.012755     ISC_z  hipp_whole
1   sub-11           2  whole_hipp      akis  0.000662     ISC_z  hipp_whole
2   sub-11           3  whole_hipp      akis  0.076620     ISC_z  hipp_whole
3   sub-11           4  whole_hipp      akis  0.022687     ISC_z  hipp_whole
4   sub-11           5  whole_hipp      akis -0.053637     ISC_z  hipp_whole

[100 rows x 7 columns]

In [311]:
classifier_df.to_csv(data_base_dir + 'classifier_rep_df.csv', index=False)

In [312]:
classifier_mean_df = classifier_df.groupby(['sub_id', 'roi', 'lith_word', 'var', 'var_group']).agg({'value': 'mean'}).reset_index()

In [313]:
classifier_mean_df.to_csv(data_base_dir + 'classifier_df.csv', index=False)

In [315]:
classifier_df.to_csv(data_dir + 'classifier_rep_df.csv', index=False)
classifier_mean_df.to_csv(data_dir + 'classifier_df.csv', index=False)

# Add features

In [17]:
classifier_df = pd.read_csv(data_base_dir + 'roi_glm_csvs/classifier_df.csv')

/Users/davidhalpern/opt/anaconda3/envs/py37/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (1) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [41]:
classifier_df = pd.concat([classifier_df, pattern_corr_adj_rel_df])

In [50]:
classifier_df.to_csv(data_base_dir + 'roi_glm_csvs/classifier_df.csv', index=False)

In [48]:
classifier_df.loc[classifier_df['var'].isin(pattern_corr_adj_rel_df['var'].unique()), 'var_group'] = 'schaefer_roi'

In [49]:
classifier_df

,subject,roi_num,lith_word,var,value,var_group
0,11,1,akis,activity,-0.160121,schaefer_roi
1,11,1,arbata,activity,0.347382,schaefer_roi
2,11,1,batas,activity,-0.210864,schaefer_roi
3,11,1,bugnas,activity,0.152934,schaefer_roi
4,11,1,burna,activity,-0.099163,schaefer_roi
...,...,...,...,...,...,...
791995,57,100,zele,pattern_sim_z_max_min,0.814529,schaefer_roi
791996,58,100,zele,pattern_sim_z_max_min,0.892038,schaefer_roi
791997,59,100,zele,pattern_sim_z_max_min,0.529827,schaefer_roi
791998,60,100,zele,pattern_sim_z_max_min,0.554586,schaefer_roi
791999,61,100,zele,pattern_sim_z_max_min,0.517471,schaefer_roi